import React from 'react';
import { type NextPage } from "next";
import Head from "next/head";
import SendSolanaForm from '~/components/SendSolanaForm';
import { useWallet } from '@solana/wallet-adapter-react';
import { Box, Stack, Typography } from '@mui/material';
import TransactionTable from '~/components/TransactionTable';

const Home: NextPage = () => {
    const { publicKey } = useWallet();
    return (
        <>
            <Head>
                <title>Solana Wallet Prototype</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                component='main'
                display='flex'
                flexDirection='column'
                alignItems='center'
                justifyContent='center'
                minHeight='86vh'
            >
                {publicKey ? (
                    <Stack mb={16} direction='row' gap={5}>
                        <Box>
                            <TransactionTable />
                        </Box>
                        <SendSolanaForm />
                    </Stack>
                ) : <Typography variant="h4">Please connect your wallet ☝️</Typography>}
            </Box>
        </>
    );
};

export default Home;
